src/Entity/Produto.php
<?php

namespace App\Entity;

use App\Repository\ProdutoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProdutoRepository::class)]
class Produto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nome = null;

    #[ORM\Column(length: 50)]
    private ?string $descricao = null;

    #[ORM\ManyToOne(inversedBy: 'produtos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categoria $categoria_id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $data_cadastro = null;

    #[ORM\Column]
    private ?float $quantidade_inicial = null;

    #[ORM\Column]
    private ?float $quantidade_disponivel = null;

    #[ORM\Column]
    private ?float $valor = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): static
    {
        $this->nome = $nome;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(string $descricao): static
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getCategoria(): ?Categoria
    {
        return $this->categoria_id;
    }

    public function setCategoriaId(?Categoria $categoria_id): static
    {
        $this->categoria_id = $categoria_id;

        return $this;
    }

    public function getDataCadastro(): ?\DateTimeInterface
    {
        return $this->data_cadastro;
    }

    public function setDataCadastro(\DateTimeInterface $data_cadastro): static
    {
        $this->data_cadastro = $data_cadastro;

        return $this;
    }

    public function getQuantidadeInicial(): ?float
    {
        return $this->quantidade_inicial;
    }

    public function setQuantidadeInicial(float $quantidade_inicial): static
    {
        $this->quantidade_inicial = $quantidade_inicial;

        return $this;
    }

    public function getQuantidadeDisponivel(): ?float
    {
        return $this->quantidade_disponivel;
    }

    public function setQuantidadeDisponivel(float $quantidade_disponivel): static
    {
        $this->quantidade_disponivel = $quantidade_disponivel;

        return $this;
    }

    public function getValor(): ?float
    {
        return $this->valor;
    }

    public function setValor(float $valor): static
    {
        $this->valor = $valor;

        return $this;
    }
}

src/Controller/Produtos/AumentarEstoqueController.php
<?php 

namespace App\Controller\Produtos;

use App\Repository\ProdutoRepository;
use App\Service\AumentarEstoqueService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AumentarEstoqueController extends AbstractController
{

    #[Route("produtos/adicionar/{id}" ,name:"produto_adicionar")]
    public function aumentarEstoque(
        int $id,
        ProdutoRepository $produtoRepository,
        AumentarEstoqueService $aumentarEstoqueService,
    ) : Response 
    {
        $produto = $produtoRepository->find($id);
        $aumentarEstoqueService->aumentarEstoque(produto: $produto);
        return $this->redirectToRoute("listar_produtos");
    }
}
?>

src/Controller/Produtos/CadastrarController.php
<?php

namespace App\Controller\Produtos;

use App\Service\CadastrarProdutoService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CadastrarController extends AbstractController
{
    
    #[Route('produtos/cadastrar', name:"cadastrar_produto_show", methods: 'GET')]
    public function show(): Response
    {
        return $this->render('app/produto/cadastrar.twig');
    }

    #[Route('produtos/cadastrar', name:"cadastrar_produto_salvar",methods: 'POST')]
    public function salvar(Request $request, CadastrarProdutoService $cadastrarProdutoService): Response
    {
        $dados = $request->request->all();//pegar todos os campos da requisição
        $cadastrarProdutoService->salvar(dados : $dados);
       
        return $this->redirectToRoute("listar_produtos");
    }
} 
?>

src/Controller/Produtos/EditarController.php
<?php

namespace App\Controller\Produtos;

use App\Repository\ProdutoRepository;
use App\Service\EditarProdutoService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EditarController extends AbstractController
{
    #[Route('produtos/editar/{id}', name: 'produto_editar')]
    public function editar(
        int $id,
        Request $request,
        ProdutoRepository $produtoRepository,
        EditarProdutoService $editarProdutoService,
    ): Response {
        // Encontra o produto pelo ID
        $produto = $produtoRepository->find($id);
    
        // Verifica se a requisição é POST para processar os dados
        if ($request->isMethod('POST')) {
            $nome = $request->request->get('nome');
            $descricao = $request->request->get('descricao');
            $qtInicial = $request->request->get('quantidadeInicial');
            $qtDisponivel = $request->request->get('quantidadeDisponivel');
            $valor = $request->request->get('valor');
    
            // Verifica se todos os valores foram recebidos
            if ($nome && $descricao && $qtInicial && $qtDisponivel && $valor) {
                $dados = [
                    "nome" => $nome,
                    "descricao" => $descricao,
                    'quantidadeInicial' => $qtInicial,
                    "quantidadeDisponivel" => $qtDisponivel,
                    'valor' => $valor,
                ];
    
                // Chama o serviço de edição, passando o produto existente
                $editarProdutoService->editar(produto : $produto, dados : $dados);
    
                // Redireciona para outra página
                return $this->redirectToRoute('listar_produtos');
            }
        }
    
        
        $data['titulo'] = "Editar produto";
        $data['produto'] = $produto; // Exibe os dados atuais do produto no formulário
    
        return $this->render("app/produto/novoProduto.html.twig", $data);
    }
    
}
?>



<!-- 
 $produto = $produtoRepository->find($id);

        if ($request->isMethod('POST')) {
            // Atualizar os campos do produto
            $produto->setNome($request->request->get('nome'));
            $produto->setDescricao($request->request->get('descricao'));
            $produto->setQuantidadeInicial($request->request->get('quantidadeInicial'));
            $produto->setQuantidadeDisponivel($request->request->get('quantidadeDisponivel'));
            $produto->setValor($request->request->get('valor'));
        }
        $em->flush();
           
      
        
        $data['titulo'] = "Editar produto";
        $data['produto'] = $produto;
        
        
        return $this->render("app/produto/novoProduto.html.twig",$data);
        return new Response();
-->

src/Controller/Produtos/ExcluirController.php
<?php

namespace App\Controller\Produtos;

use App\Repository\ProdutoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ExcluirController extends AbstractController
{
    #[Route('categorias/excluir/{id}', name: 'produto_excluir')]
    public function excluir(
        int $id,
        EntityManagerInterface $em,
        ProdutoRepository $produtoRepository,
    ): Response 
    {
        $produto = $produtoRepository->find($id);

     
        $em->remove($produto);
        $em->flush();

        return $this->redirectToRoute("listar_produtos");
    }
}
?>

src/Controller/Produtos/ListarController.php
<?php 
namespace App\Controller\Produtos;

use App\Repository\ProdutoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ListarController extends AbstractController
{

    public function __construct(
        private ProdutoRepository $produtoRepository
    )
    {
    }

    #[Route('/produtos', name:"listar_produtos", methods:'GET')]
    public function show(): Response
    {
       return $this->render('app/produto/listar.html.twig',[
        'produtos' => $this->produtoRepository->findAll(),
       ]);
    }
}
?>

src/Controller/Produtos/VendaController.php
<?php

namespace App\Controller\Produtos;

use App\Repository\ProdutoRepository;
use App\Service\AumentarEstoqueService;
use App\Service\DiminuirEstoqueService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VendaController extends AbstractController
{
    #[Route('produtos/vender/{id}', name: 'produto_vender')]
    function diminuirEstoque(
        int $id,
        DiminuirEstoqueService $diminuirEstoqueService,
        ProdutoRepository $produtoRepository,
    ) : Response 
    {
        $produto = $produtoRepository->find($id);
        $diminuirEstoqueService->diminuirEstoque(produto : $produto);
        return $this->redirectToRoute("listar_produtos");
    }
}

?>

templates/app/produto/cadastrar.twig
{% extends 'base.html.twig' %}

{% block body %}
   {% include "header.html.twig" %}

  <div class="container py-5">
    <div class="mb-4">
      <h1>Novo produto</h1>
    </div>

    <div class="w-50 mt-2">
       {% include "mensagens.html.twig" %} 
      <form action="{{ path('cadastrar_produto_salvar') }}" method="POST">
          <div class="mb-3">
            <label for="nome" class="form-label">Nome:</label>
            <input type="text" class="form-control" id="nome" name="nome" required minlength="2">
          </div>
          <div class="mb-3">
            <label for="descricao" class="form-label">Descrição:</label>
            <textarea class="form-control" id="descricao" name="descricao" style="resize:none;" rows="5"></textarea>
          </div>


          <div class="row">
            <div class="mb-3 col-4">
              <label for="categoriaId" class="form-label">Categoria Id:</label>
              <input type="number" class="form-control" id="categoriaId" name="categoriaId">
            </div>
            <div class="mb-3 col-4">
              <label for="quantidade" class="form-label">Quantidade:</label>
              <input type="number" class="form-control" id="quantidade" name="quantidade">
            </div>
            <div class="mb-3 col-4">
              <label for="valor" class="form-label">Valor:</label>
              <input type="text" class="form-control" id="valor" name="valor">
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Salvar</button>
      </form> 
     
    </div>
  </div>
{% endblock %}

templates/app/produto/listar.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   {% include "header.html.twig" %}

      <div class="container py-5">
      <div class="mb-4">
        <h1>Produtos</h1>
        <div>
          <a href="/produtos/cadastrar" class="btn btn-primary"><i class="bi bi-plus"></i>Novo produto</a>
        </div>
      </div>

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Nome</th>
            <th scope="col">descrição</th>
            <th scope="col">categoria_id</th>
            <th scope="col-2 text-align-right">data_cadastro</th>
            <th scope="col-2 text-align-right">quantidade_inicial</th>
            <th scope="col-2 text-align-right">quantidade_disponiviel</th>
            <th scope="col-2 text-align-right">valor</th>
          </tr>
        </thead>
        <tbody>
            {% for valor in produtos %}  
                 <tr>
                    <th scope='row'>{{ valor.id }}</th>
                    <td>{{ valor.nome }}</td>
                    <td>{{ valor.descricao }}</td>
                    <td>{{ valor.categoria.id }}</td>  
                    <td>{{ valor.dataCadastro|date("d/m/Y") }}</td> 
                    <td>{{ valor.quantidadeInicial}}</td> 
                    <td>{{ valor.quantidadeDisponivel }}</td>  
                    <td>{{ valor.valor }}</td> 
                    <td class='col-2 text-align-right'>
                      <a href="{{ path('produto_adicionar', {id: valor.id}) }}"  class='btn btn-primary btn-sm'><i class='bi bi-plus'></i></a>
                      <a href="{{ path('produto_editar', {id: valor.id}) }}" class='btn btn-secondary btn-sm'><i class='bi bi-pencil'></i></a>
                      <a href='{{ path('produto_excluir', {id: valor.id}) }}' class='btn btn-danger btn-sm'><i class='bi bi-x'></i></a>
                      <a href="{{ path('produto_vender', {id: valor.id}) }}" class='btn btn-primary btn-sm'>Vender</a>
                    </td>
                  </tr> 
            {% endfor %}        
        </tbody>

      </table>
    </div>
 

{% endblock %}

templates/app/produto/novoProduto.html.twig
{% extends "base.html.twig" %}
{% block title %} {{ titulo }} {% endblock %}

{% block body %}
    {% include "header.html.twig" %}
    <div class="container py-5">
      <div class="mb-4">
        <h1>Editar produto</h1>
      </div>

      <div class="w-50 mt-2">
        <form  action="{{ path('produto_editar', { id: produto.id }) }}" method="POST">
          <div class="mb-3">
            <label for="nome" class="form-label">Nome:</label>
            <input type="text" class="form-control" id="nome" name="nome" required minlength="2" placeholder="{{ produto.nome }}">
            
          </div>
          <div class="mb-3">
            <label for="descricao" class="form-label">Descrição:</label>
            <textarea class="form-control" id="descricao" name="descricao" style="resize:none;" rows="5" placeholder="{{ produto.descricao }}"></textarea>
          </div>


          <div class="row">
            <div class="mb-3 col-4">
              <label for="categoriaId" class="form-label">Categoria Id:</label>
              <input type="number" class="form-control" id="categoriaId" name="categoriaId" placeholder="{{ produto.categoria.id }}" readonly>
            </div>
            <div class="mb-3 col-4">
              <label for="quantidade" class="form-label">Quantidade inicial:</label>
              <input type="number" class="form-control" id="quantidade" name="quantidadeInicial" placeholder="{{ produto.quantidadeInicial }}">
            </div>
             <div class="mb-3 col-4">
              <label for="quantidade" class="form-label">Quantidade disponivel:</label>
              <input type="number" class="form-control" id="quantidade" name="quantidadeDisponivel" placeholder="{{ produto.quantidadeDisponivel }}">
            </div>
            <div class="mb-3 col-4">
              <label for="valor" class="form-label">Valor:</label>
              <input type="text" class="form-control" id="valor" name="valor" placeholder="{{ produto.valor }}">
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
      </div>
    </div>
{% endblock %}